version: '{build}-{branch}'
image: Visual Studio 2017
build_script:
- ps: "dotnet restore src\\Prometheus.Client \ndotnet build src\\Prometheus.Client -c Release\nif($env:APPVEYOR_REPO_TAG -eq \"false\") {\n    dotnet pack src\\Prometheus.Client --include-symbols --no-build --version-suffix build-$env:APPVEYOR_BUILD_NUMBER -o artifacts\\myget -c Release\n}\nif($env:APPVEYOR_REPO_TAG -eq \"true\") {\n    dotnet pack src\\Prometheus.Client --include-symbols --no-build -o artifacts\\nuget -c Release\n}"
test_script:
- ps: dotnet test tests\Prometheus.Client.Tests\Prometheus.Client.Tests.csproj -c Release
artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: Nuget
- path: '**\artifacts\myget\*.nupkg'
  name: Myget
deploy:
- provider: NuGet
  api_key:
    secure: vukCl5k+S4fJtqeYNiB9ufy/NUCw+60cPcqnPoqvykBjSo8Ub8QtEfZNN9qvj5Jh
  artifact: NuGet
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/phnx47-beta/api/v2/package
  api_key:
    secure: sra89qUYhiuc146gUszl0lg1u3tWG1Zc65B7lgVuZlIfxyq/3w4q3mkXeBiLpNA5
  symbol_server: https://www.myget.org/F/phnx47-beta/symbols/api/v2/package
  artifact: MyGet
  on:
    branch: master
    appveyor_repo_tag: false